// Code generated by MockGen. DO NOT EDIT.
// Source: settings/provider.go
//
// Generated by this command:
//
//	mockgen -source=settings/provider.go -destination=internal/mocks/mock_settings_provider.go -package=mocks SettingsProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	settings "server/settings"

	gomock "go.uber.org/mock/gomock"
)

// MockSettingsProvider is a mock of SettingsProvider interface.
type MockSettingsProvider struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsProviderMockRecorder
	isgomock struct{}
}

// MockSettingsProviderMockRecorder is the mock recorder for MockSettingsProvider.
type MockSettingsProviderMockRecorder struct {
	mock *MockSettingsProvider
}

// NewMockSettingsProvider creates a new mock instance.
func NewMockSettingsProvider(ctrl *gomock.Controller) *MockSettingsProvider {
	mock := &MockSettingsProvider{ctrl: ctrl}
	mock.recorder = &MockSettingsProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingsProvider) EXPECT() *MockSettingsProviderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSettingsProvider) Get() *settings.BTSets {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(*settings.BTSets)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockSettingsProviderMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSettingsProvider)(nil).Get))
}

// GetStaticConfig mocks base method.
func (m *MockSettingsProvider) GetStaticConfig() settings.StaticConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStaticConfig")
	ret0, _ := ret[0].(settings.StaticConfig)
	return ret0
}

// GetStaticConfig indicates an expected call of GetStaticConfig.
func (mr *MockSettingsProviderMockRecorder) GetStaticConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStaticConfig", reflect.TypeOf((*MockSettingsProvider)(nil).GetStaticConfig))
}

// GetStoragePreferences mocks base method.
func (m *MockSettingsProvider) GetStoragePreferences() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoragePreferences")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// GetStoragePreferences indicates an expected call of GetStoragePreferences.
func (mr *MockSettingsProviderMockRecorder) GetStoragePreferences() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoragePreferences", reflect.TypeOf((*MockSettingsProvider)(nil).GetStoragePreferences))
}

// ReadOnly mocks base method.
func (m *MockSettingsProvider) ReadOnly() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadOnly")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ReadOnly indicates an expected call of ReadOnly.
func (mr *MockSettingsProviderMockRecorder) ReadOnly() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadOnly", reflect.TypeOf((*MockSettingsProvider)(nil).ReadOnly))
}

// Set mocks base method.
func (m *MockSettingsProvider) Set(sets *settings.BTSets) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", sets)
}

// Set indicates an expected call of Set.
func (mr *MockSettingsProviderMockRecorder) Set(sets any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockSettingsProvider)(nil).Set), sets)
}
