// Code generated by MockGen. DO NOT EDIT.
// Source: torr/service.go
//
// Generated by this command:
//
//	mockgen -source=torr/service.go -destination=internal/mocks/mock_torrent_service.go -package=mocks TorrentService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	torr "server/torr"
	storage "server/torr/storage"

	torrent "github.com/anacrolix/torrent"
	gomock "go.uber.org/mock/gomock"
)

// MockTorrentService is a mock of TorrentService interface.
type MockTorrentService struct {
	ctrl     *gomock.Controller
	recorder *MockTorrentServiceMockRecorder
	isgomock struct{}
}

// MockTorrentServiceMockRecorder is the mock recorder for MockTorrentService.
type MockTorrentServiceMockRecorder struct {
	mock *MockTorrentService
}

// NewMockTorrentService creates a new mock instance.
func NewMockTorrentService(ctrl *gomock.Controller) *MockTorrentService {
	mock := &MockTorrentService{ctrl: ctrl}
	mock.recorder = &MockTorrentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTorrentService) EXPECT() *MockTorrentServiceMockRecorder {
	return m.recorder
}

// AddTorrent mocks base method.
func (m *MockTorrentService) AddTorrent(spec *torrent.TorrentSpec, title, poster, data, category string) (*torr.Torrent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTorrent", spec, title, poster, data, category)
	ret0, _ := ret[0].(*torr.Torrent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTorrent indicates an expected call of AddTorrent.
func (mr *MockTorrentServiceMockRecorder) AddTorrent(spec, title, poster, data, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTorrent", reflect.TypeOf((*MockTorrentService)(nil).AddTorrent), spec, title, poster, data, category)
}

// DropTorrent mocks base method.
func (m *MockTorrentService) DropTorrent(hash string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DropTorrent", hash)
}

// DropTorrent indicates an expected call of DropTorrent.
func (mr *MockTorrentServiceMockRecorder) DropTorrent(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropTorrent", reflect.TypeOf((*MockTorrentService)(nil).DropTorrent), hash)
}

// GetTorrent mocks base method.
func (m *MockTorrentService) GetTorrent(hash string) *torr.Torrent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTorrent", hash)
	ret0, _ := ret[0].(*torr.Torrent)
	return ret0
}

// GetTorrent indicates an expected call of GetTorrent.
func (mr *MockTorrentServiceMockRecorder) GetTorrent(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTorrent", reflect.TypeOf((*MockTorrentService)(nil).GetTorrent), hash)
}

// GetTorrentDB mocks base method.
func (m *MockTorrentService) GetTorrentDB(hash string) *torr.Torrent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTorrentDB", hash)
	ret0, _ := ret[0].(*torr.Torrent)
	return ret0
}

// GetTorrentDB indicates an expected call of GetTorrentDB.
func (mr *MockTorrentServiceMockRecorder) GetTorrentDB(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTorrentDB", reflect.TypeOf((*MockTorrentService)(nil).GetTorrentDB), hash)
}

// ListTorrents mocks base method.
func (m *MockTorrentService) ListTorrents() []*torr.Torrent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTorrents")
	ret0, _ := ret[0].([]*torr.Torrent)
	return ret0
}

// ListTorrents indicates an expected call of ListTorrents.
func (mr *MockTorrentServiceMockRecorder) ListTorrents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTorrents", reflect.TypeOf((*MockTorrentService)(nil).ListTorrents))
}

// LoadTorrent mocks base method.
func (m *MockTorrentService) LoadTorrent(tor *torr.Torrent) *torr.Torrent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadTorrent", tor)
	ret0, _ := ret[0].(*torr.Torrent)
	return ret0
}

// LoadTorrent indicates an expected call of LoadTorrent.
func (mr *MockTorrentServiceMockRecorder) LoadTorrent(tor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadTorrent", reflect.TypeOf((*MockTorrentService)(nil).LoadTorrent), tor)
}

// RemoveTorrent mocks base method.
func (m *MockTorrentService) RemoveTorrent(hash string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveTorrent", hash)
}

// RemoveTorrent indicates an expected call of RemoveTorrent.
func (mr *MockTorrentServiceMockRecorder) RemoveTorrent(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTorrent", reflect.TypeOf((*MockTorrentService)(nil).RemoveTorrent), hash)
}

// SetTorrent mocks base method.
func (m *MockTorrentService) SetTorrent(hash, title, poster, category, data string) *torr.Torrent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTorrent", hash, title, poster, category, data)
	ret0, _ := ret[0].(*torr.Torrent)
	return ret0
}

// SetTorrent indicates an expected call of SetTorrent.
func (mr *MockTorrentServiceMockRecorder) SetTorrent(hash, title, poster, category, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTorrent", reflect.TypeOf((*MockTorrentService)(nil).SetTorrent), hash, title, poster, category, data)
}

// MockStorageProvider is a mock of StorageProvider interface.
type MockStorageProvider struct {
	ctrl     *gomock.Controller
	recorder *MockStorageProviderMockRecorder
	isgomock struct{}
}

// MockStorageProviderMockRecorder is the mock recorder for MockStorageProvider.
type MockStorageProviderMockRecorder struct {
	mock *MockStorageProvider
}

// NewMockStorageProvider creates a new mock instance.
func NewMockStorageProvider(ctrl *gomock.Controller) *MockStorageProvider {
	mock := &MockStorageProvider{ctrl: ctrl}
	mock.recorder = &MockStorageProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageProvider) EXPECT() *MockStorageProviderMockRecorder {
	return m.recorder
}

// Storage mocks base method.
func (m *MockStorageProvider) Storage() storage.Storage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Storage")
	ret0, _ := ret[0].(storage.Storage)
	return ret0
}

// Storage indicates an expected call of Storage.
func (mr *MockStorageProviderMockRecorder) Storage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Storage", reflect.TypeOf((*MockStorageProvider)(nil).Storage))
}
