// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/contracts/contracts.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/contracts/contracts.go -destination=internal/mocks/mock_api_contracts.go -package=mocks -mock_names TorrentHandle=MockAPITorrentHandle,TorrentService=MockAPITorrentService,SettingsService=MockAPISettingsService,ViewedService=MockAPIViewedService,SystemService=MockAPISystemService,SearchService=MockAPISearchService,MediaService=MockAPIMediaService,ModulesService=MockAPIModulesService,StreamService=MockAPIStreamService,PlaybackService=MockAPIPlaybackService TorrentHandle,TorrentService,SettingsService,ViewedService,SystemService,SearchService,MediaService,ModulesService,StreamService,PlaybackService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	io "io"
	http "net/http"
	reflect "reflect"
	contracts "server/internal/app/contracts"
	settings "server/settings"
	state "server/torr/state"

	gomock "go.uber.org/mock/gomock"
	ffprobe "gopkg.in/vansante/go-ffprobe.v2"
)

// MockTorrentSpecPayload is a mock of TorrentSpecPayload interface.
type MockTorrentSpecPayload struct {
	ctrl     *gomock.Controller
	recorder *MockTorrentSpecPayloadMockRecorder
	isgomock struct{}
}

// MockTorrentSpecPayloadMockRecorder is the mock recorder for MockTorrentSpecPayload.
type MockTorrentSpecPayloadMockRecorder struct {
	mock *MockTorrentSpecPayload
}

// NewMockTorrentSpecPayload creates a new mock instance.
func NewMockTorrentSpecPayload(ctrl *gomock.Controller) *MockTorrentSpecPayload {
	mock := &MockTorrentSpecPayload{ctrl: ctrl}
	mock.recorder = &MockTorrentSpecPayloadMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTorrentSpecPayload) EXPECT() *MockTorrentSpecPayloadMockRecorder {
	return m.recorder
}

// TorrentSpecPayload mocks base method.
func (m *MockTorrentSpecPayload) TorrentSpecPayload() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TorrentSpecPayload")
}

// TorrentSpecPayload indicates an expected call of TorrentSpecPayload.
func (mr *MockTorrentSpecPayloadMockRecorder) TorrentSpecPayload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TorrentSpecPayload", reflect.TypeOf((*MockTorrentSpecPayload)(nil).TorrentSpecPayload))
}

// MockAPITorrentHandle is a mock of TorrentHandle interface.
type MockAPITorrentHandle struct {
	ctrl     *gomock.Controller
	recorder *MockAPITorrentHandleMockRecorder
	isgomock struct{}
}

// MockAPITorrentHandleMockRecorder is the mock recorder for MockAPITorrentHandle.
type MockAPITorrentHandleMockRecorder struct {
	mock *MockAPITorrentHandle
}

// NewMockAPITorrentHandle creates a new mock instance.
func NewMockAPITorrentHandle(ctrl *gomock.Controller) *MockAPITorrentHandle {
	mock := &MockAPITorrentHandle{ctrl: ctrl}
	mock.recorder = &MockAPITorrentHandleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPITorrentHandle) EXPECT() *MockAPITorrentHandleMockRecorder {
	return m.recorder
}

// EnsureTitleFromInfo mocks base method.
func (m *MockAPITorrentHandle) EnsureTitleFromInfo() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EnsureTitleFromInfo")
}

// EnsureTitleFromInfo indicates an expected call of EnsureTitleFromInfo.
func (mr *MockAPITorrentHandleMockRecorder) EnsureTitleFromInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureTitleFromInfo", reflect.TypeOf((*MockAPITorrentHandle)(nil).EnsureTitleFromInfo))
}

// FileCount mocks base method.
func (m *MockAPITorrentHandle) FileCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// FileCount indicates an expected call of FileCount.
func (mr *MockAPITorrentHandleMockRecorder) FileCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileCount", reflect.TypeOf((*MockAPITorrentHandle)(nil).FileCount))
}

// HashHex mocks base method.
func (m *MockAPITorrentHandle) HashHex() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashHex")
	ret0, _ := ret[0].(string)
	return ret0
}

// HashHex indicates an expected call of HashHex.
func (mr *MockAPITorrentHandleMockRecorder) HashHex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashHex", reflect.TypeOf((*MockAPITorrentHandle)(nil).HashHex))
}

// Metadata mocks base method.
func (m *MockAPITorrentHandle) Metadata() contracts.StreamMeta {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metadata")
	ret0, _ := ret[0].(contracts.StreamMeta)
	return ret0
}

// Metadata indicates an expected call of Metadata.
func (mr *MockAPITorrentHandleMockRecorder) Metadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metadata", reflect.TypeOf((*MockAPITorrentHandle)(nil).Metadata))
}

// Name mocks base method.
func (m *MockAPITorrentHandle) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockAPITorrentHandleMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockAPITorrentHandle)(nil).Name))
}

// Ready mocks base method.
func (m *MockAPITorrentHandle) Ready() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ready")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Ready indicates an expected call of Ready.
func (mr *MockAPITorrentHandleMockRecorder) Ready() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ready", reflect.TypeOf((*MockAPITorrentHandle)(nil).Ready))
}

// State mocks base method.
func (m *MockAPITorrentHandle) State() state.TorrentStat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "State")
	ret0, _ := ret[0].(state.TorrentStat)
	return ret0
}

// State indicates an expected call of State.
func (mr *MockAPITorrentHandleMockRecorder) State() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "State", reflect.TypeOf((*MockAPITorrentHandle)(nil).State))
}

// Status mocks base method.
func (m *MockAPITorrentHandle) Status() *state.TorrentStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(*state.TorrentStatus)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockAPITorrentHandleMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockAPITorrentHandle)(nil).Status))
}

// Stream mocks base method.
func (m *MockAPITorrentHandle) Stream(index int, request *http.Request, writer http.ResponseWriter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stream", index, request, writer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stream indicates an expected call of Stream.
func (mr *MockAPITorrentHandleMockRecorder) Stream(index, request, writer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stream", reflect.TypeOf((*MockAPITorrentHandle)(nil).Stream), index, request, writer)
}

// MockTorrentCreator is a mock of TorrentCreator interface.
type MockTorrentCreator struct {
	ctrl     *gomock.Controller
	recorder *MockTorrentCreatorMockRecorder
	isgomock struct{}
}

// MockTorrentCreatorMockRecorder is the mock recorder for MockTorrentCreator.
type MockTorrentCreatorMockRecorder struct {
	mock *MockTorrentCreator
}

// NewMockTorrentCreator creates a new mock instance.
func NewMockTorrentCreator(ctrl *gomock.Controller) *MockTorrentCreator {
	mock := &MockTorrentCreator{ctrl: ctrl}
	mock.recorder = &MockTorrentCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTorrentCreator) EXPECT() *MockTorrentCreatorMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockTorrentCreator) Add(spec contracts.TorrentSpec, title, poster, data, category string) (contracts.TorrentHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", spec, title, poster, data, category)
	ret0, _ := ret[0].(contracts.TorrentHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockTorrentCreatorMockRecorder) Add(spec, title, poster, data, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockTorrentCreator)(nil).Add), spec, title, poster, data, category)
}

// MockTorrentLookup is a mock of TorrentLookup interface.
type MockTorrentLookup struct {
	ctrl     *gomock.Controller
	recorder *MockTorrentLookupMockRecorder
	isgomock struct{}
}

// MockTorrentLookupMockRecorder is the mock recorder for MockTorrentLookup.
type MockTorrentLookupMockRecorder struct {
	mock *MockTorrentLookup
}

// NewMockTorrentLookup creates a new mock instance.
func NewMockTorrentLookup(ctrl *gomock.Controller) *MockTorrentLookup {
	mock := &MockTorrentLookup{ctrl: ctrl}
	mock.recorder = &MockTorrentLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTorrentLookup) EXPECT() *MockTorrentLookupMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockTorrentLookup) Get(hash string) contracts.TorrentHandle {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", hash)
	ret0, _ := ret[0].(contracts.TorrentHandle)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockTorrentLookupMockRecorder) Get(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTorrentLookup)(nil).Get), hash)
}

// IsStored mocks base method.
func (m *MockTorrentLookup) IsStored(tor contracts.TorrentHandle) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsStored", tor)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsStored indicates an expected call of IsStored.
func (mr *MockTorrentLookupMockRecorder) IsStored(tor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsStored", reflect.TypeOf((*MockTorrentLookup)(nil).IsStored), tor)
}

// Status mocks base method.
func (m *MockTorrentLookup) Status(tor contracts.TorrentHandle) *state.TorrentStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", tor)
	ret0, _ := ret[0].(*state.TorrentStatus)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockTorrentLookupMockRecorder) Status(tor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockTorrentLookup)(nil).Status), tor)
}

// StatusByHash mocks base method.
func (m *MockTorrentLookup) StatusByHash(hash string) (*state.TorrentStatus, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatusByHash", hash)
	ret0, _ := ret[0].(*state.TorrentStatus)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// StatusByHash indicates an expected call of StatusByHash.
func (mr *MockTorrentLookupMockRecorder) StatusByHash(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatusByHash", reflect.TypeOf((*MockTorrentLookup)(nil).StatusByHash), hash)
}

// MockTorrentCatalog is a mock of TorrentCatalog interface.
type MockTorrentCatalog struct {
	ctrl     *gomock.Controller
	recorder *MockTorrentCatalogMockRecorder
	isgomock struct{}
}

// MockTorrentCatalogMockRecorder is the mock recorder for MockTorrentCatalog.
type MockTorrentCatalogMockRecorder struct {
	mock *MockTorrentCatalog
}

// NewMockTorrentCatalog creates a new mock instance.
func NewMockTorrentCatalog(ctrl *gomock.Controller) *MockTorrentCatalog {
	mock := &MockTorrentCatalog{ctrl: ctrl}
	mock.recorder = &MockTorrentCatalogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTorrentCatalog) EXPECT() *MockTorrentCatalogMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockTorrentCatalog) List() []contracts.TorrentHandle {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]contracts.TorrentHandle)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockTorrentCatalogMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTorrentCatalog)(nil).List))
}

// ListHashes mocks base method.
func (m *MockTorrentCatalog) ListHashes() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHashes")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ListHashes indicates an expected call of ListHashes.
func (mr *MockTorrentCatalogMockRecorder) ListHashes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHashes", reflect.TypeOf((*MockTorrentCatalog)(nil).ListHashes))
}

// Statuses mocks base method.
func (m *MockTorrentCatalog) Statuses() []*state.TorrentStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Statuses")
	ret0, _ := ret[0].([]*state.TorrentStatus)
	return ret0
}

// Statuses indicates an expected call of Statuses.
func (mr *MockTorrentCatalogMockRecorder) Statuses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Statuses", reflect.TypeOf((*MockTorrentCatalog)(nil).Statuses))
}

// MockTorrentMutation is a mock of TorrentMutation interface.
type MockTorrentMutation struct {
	ctrl     *gomock.Controller
	recorder *MockTorrentMutationMockRecorder
	isgomock struct{}
}

// MockTorrentMutationMockRecorder is the mock recorder for MockTorrentMutation.
type MockTorrentMutationMockRecorder struct {
	mock *MockTorrentMutation
}

// NewMockTorrentMutation creates a new mock instance.
func NewMockTorrentMutation(ctrl *gomock.Controller) *MockTorrentMutation {
	mock := &MockTorrentMutation{ctrl: ctrl}
	mock.recorder = &MockTorrentMutationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTorrentMutation) EXPECT() *MockTorrentMutationMockRecorder {
	return m.recorder
}

// Drop mocks base method.
func (m *MockTorrentMutation) Drop(hash string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Drop", hash)
}

// Drop indicates an expected call of Drop.
func (mr *MockTorrentMutationMockRecorder) Drop(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Drop", reflect.TypeOf((*MockTorrentMutation)(nil).Drop), hash)
}

// DropReadiness mocks base method.
func (m *MockTorrentMutation) DropReadiness(hash string) contracts.DropReadiness {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DropReadiness", hash)
	ret0, _ := ret[0].(contracts.DropReadiness)
	return ret0
}

// DropReadiness indicates an expected call of DropReadiness.
func (mr *MockTorrentMutationMockRecorder) DropReadiness(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropReadiness", reflect.TypeOf((*MockTorrentMutation)(nil).DropReadiness), hash)
}

// EnqueueMetadataFinalize mocks base method.
func (m *MockTorrentMutation) EnqueueMetadataFinalize(tor contracts.TorrentHandle, spec *contracts.TorrentSpec, saveToDB bool) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueMetadataFinalize", tor, spec, saveToDB)
	ret0, _ := ret[0].(bool)
	return ret0
}

// EnqueueMetadataFinalize indicates an expected call of EnqueueMetadataFinalize.
func (mr *MockTorrentMutationMockRecorder) EnqueueMetadataFinalize(tor, spec, saveToDB any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueMetadataFinalize", reflect.TypeOf((*MockTorrentMutation)(nil).EnqueueMetadataFinalize), tor, spec, saveToDB)
}

// EnqueuePreload mocks base method.
func (m *MockTorrentMutation) EnqueuePreload(tor contracts.TorrentHandle, index int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueuePreload", tor, index)
	ret0, _ := ret[0].(bool)
	return ret0
}

// EnqueuePreload indicates an expected call of EnqueuePreload.
func (mr *MockTorrentMutationMockRecorder) EnqueuePreload(tor, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueuePreload", reflect.TypeOf((*MockTorrentMutation)(nil).EnqueuePreload), tor, index)
}

// Remove mocks base method.
func (m *MockTorrentMutation) Remove(hash string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Remove", hash)
}

// Remove indicates an expected call of Remove.
func (mr *MockTorrentMutationMockRecorder) Remove(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockTorrentMutation)(nil).Remove), hash)
}

// SaveToDB mocks base method.
func (m *MockTorrentMutation) SaveToDB(tor contracts.TorrentHandle) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveToDB", tor)
}

// SaveToDB indicates an expected call of SaveToDB.
func (mr *MockTorrentMutationMockRecorder) SaveToDB(tor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToDB", reflect.TypeOf((*MockTorrentMutation)(nil).SaveToDB), tor)
}

// Set mocks base method.
func (m *MockTorrentMutation) Set(hash, title, poster, category, data string) contracts.TorrentHandle {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", hash, title, poster, category, data)
	ret0, _ := ret[0].(contracts.TorrentHandle)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockTorrentMutationMockRecorder) Set(hash, title, poster, category, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockTorrentMutation)(nil).Set), hash, title, poster, category, data)
}

// MockTorrentStorage is a mock of TorrentStorage interface.
type MockTorrentStorage struct {
	ctrl     *gomock.Controller
	recorder *MockTorrentStorageMockRecorder
	isgomock struct{}
}

// MockTorrentStorageMockRecorder is the mock recorder for MockTorrentStorage.
type MockTorrentStorageMockRecorder struct {
	mock *MockTorrentStorage
}

// NewMockTorrentStorage creates a new mock instance.
func NewMockTorrentStorage(ctrl *gomock.Controller) *MockTorrentStorage {
	mock := &MockTorrentStorage{ctrl: ctrl}
	mock.recorder = &MockTorrentStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTorrentStorage) EXPECT() *MockTorrentStorageMockRecorder {
	return m.recorder
}

// CacheStateByHash mocks base method.
func (m *MockTorrentStorage) CacheStateByHash(hash string) (any, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CacheStateByHash", hash)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// CacheStateByHash indicates an expected call of CacheStateByHash.
func (mr *MockTorrentStorageMockRecorder) CacheStateByHash(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheStateByHash", reflect.TypeOf((*MockTorrentStorage)(nil).CacheStateByHash), hash)
}

// MockTorrentLoader is a mock of TorrentLoader interface.
type MockTorrentLoader struct {
	ctrl     *gomock.Controller
	recorder *MockTorrentLoaderMockRecorder
	isgomock struct{}
}

// MockTorrentLoaderMockRecorder is the mock recorder for MockTorrentLoader.
type MockTorrentLoaderMockRecorder struct {
	mock *MockTorrentLoader
}

// NewMockTorrentLoader creates a new mock instance.
func NewMockTorrentLoader(ctrl *gomock.Controller) *MockTorrentLoader {
	mock := &MockTorrentLoader{ctrl: ctrl}
	mock.recorder = &MockTorrentLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTorrentLoader) EXPECT() *MockTorrentLoaderMockRecorder {
	return m.recorder
}

// LoadFromDB mocks base method.
func (m *MockTorrentLoader) LoadFromDB(tor contracts.TorrentHandle) contracts.TorrentHandle {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadFromDB", tor)
	ret0, _ := ret[0].(contracts.TorrentHandle)
	return ret0
}

// LoadFromDB indicates an expected call of LoadFromDB.
func (mr *MockTorrentLoaderMockRecorder) LoadFromDB(tor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadFromDB", reflect.TypeOf((*MockTorrentLoader)(nil).LoadFromDB), tor)
}

// MockTorrentQueryService is a mock of TorrentQueryService interface.
type MockTorrentQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockTorrentQueryServiceMockRecorder
	isgomock struct{}
}

// MockTorrentQueryServiceMockRecorder is the mock recorder for MockTorrentQueryService.
type MockTorrentQueryServiceMockRecorder struct {
	mock *MockTorrentQueryService
}

// NewMockTorrentQueryService creates a new mock instance.
func NewMockTorrentQueryService(ctrl *gomock.Controller) *MockTorrentQueryService {
	mock := &MockTorrentQueryService{ctrl: ctrl}
	mock.recorder = &MockTorrentQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTorrentQueryService) EXPECT() *MockTorrentQueryServiceMockRecorder {
	return m.recorder
}

// CacheStateByHash mocks base method.
func (m *MockTorrentQueryService) CacheStateByHash(hash string) (any, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CacheStateByHash", hash)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// CacheStateByHash indicates an expected call of CacheStateByHash.
func (mr *MockTorrentQueryServiceMockRecorder) CacheStateByHash(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheStateByHash", reflect.TypeOf((*MockTorrentQueryService)(nil).CacheStateByHash), hash)
}

// Get mocks base method.
func (m *MockTorrentQueryService) Get(hash string) contracts.TorrentHandle {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", hash)
	ret0, _ := ret[0].(contracts.TorrentHandle)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockTorrentQueryServiceMockRecorder) Get(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTorrentQueryService)(nil).Get), hash)
}

// IsStored mocks base method.
func (m *MockTorrentQueryService) IsStored(tor contracts.TorrentHandle) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsStored", tor)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsStored indicates an expected call of IsStored.
func (mr *MockTorrentQueryServiceMockRecorder) IsStored(tor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsStored", reflect.TypeOf((*MockTorrentQueryService)(nil).IsStored), tor)
}

// List mocks base method.
func (m *MockTorrentQueryService) List() []contracts.TorrentHandle {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]contracts.TorrentHandle)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockTorrentQueryServiceMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTorrentQueryService)(nil).List))
}

// ListHashes mocks base method.
func (m *MockTorrentQueryService) ListHashes() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHashes")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ListHashes indicates an expected call of ListHashes.
func (mr *MockTorrentQueryServiceMockRecorder) ListHashes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHashes", reflect.TypeOf((*MockTorrentQueryService)(nil).ListHashes))
}

// Status mocks base method.
func (m *MockTorrentQueryService) Status(tor contracts.TorrentHandle) *state.TorrentStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", tor)
	ret0, _ := ret[0].(*state.TorrentStatus)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockTorrentQueryServiceMockRecorder) Status(tor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockTorrentQueryService)(nil).Status), tor)
}

// StatusByHash mocks base method.
func (m *MockTorrentQueryService) StatusByHash(hash string) (*state.TorrentStatus, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatusByHash", hash)
	ret0, _ := ret[0].(*state.TorrentStatus)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// StatusByHash indicates an expected call of StatusByHash.
func (mr *MockTorrentQueryServiceMockRecorder) StatusByHash(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatusByHash", reflect.TypeOf((*MockTorrentQueryService)(nil).StatusByHash), hash)
}

// Statuses mocks base method.
func (m *MockTorrentQueryService) Statuses() []*state.TorrentStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Statuses")
	ret0, _ := ret[0].([]*state.TorrentStatus)
	return ret0
}

// Statuses indicates an expected call of Statuses.
func (mr *MockTorrentQueryServiceMockRecorder) Statuses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Statuses", reflect.TypeOf((*MockTorrentQueryService)(nil).Statuses))
}

// MockTorrentCommandService is a mock of TorrentCommandService interface.
type MockTorrentCommandService struct {
	ctrl     *gomock.Controller
	recorder *MockTorrentCommandServiceMockRecorder
	isgomock struct{}
}

// MockTorrentCommandServiceMockRecorder is the mock recorder for MockTorrentCommandService.
type MockTorrentCommandServiceMockRecorder struct {
	mock *MockTorrentCommandService
}

// NewMockTorrentCommandService creates a new mock instance.
func NewMockTorrentCommandService(ctrl *gomock.Controller) *MockTorrentCommandService {
	mock := &MockTorrentCommandService{ctrl: ctrl}
	mock.recorder = &MockTorrentCommandServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTorrentCommandService) EXPECT() *MockTorrentCommandServiceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockTorrentCommandService) Add(spec contracts.TorrentSpec, title, poster, data, category string) (contracts.TorrentHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", spec, title, poster, data, category)
	ret0, _ := ret[0].(contracts.TorrentHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockTorrentCommandServiceMockRecorder) Add(spec, title, poster, data, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockTorrentCommandService)(nil).Add), spec, title, poster, data, category)
}

// Drop mocks base method.
func (m *MockTorrentCommandService) Drop(hash string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Drop", hash)
}

// Drop indicates an expected call of Drop.
func (mr *MockTorrentCommandServiceMockRecorder) Drop(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Drop", reflect.TypeOf((*MockTorrentCommandService)(nil).Drop), hash)
}

// DropReadiness mocks base method.
func (m *MockTorrentCommandService) DropReadiness(hash string) contracts.DropReadiness {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DropReadiness", hash)
	ret0, _ := ret[0].(contracts.DropReadiness)
	return ret0
}

// DropReadiness indicates an expected call of DropReadiness.
func (mr *MockTorrentCommandServiceMockRecorder) DropReadiness(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropReadiness", reflect.TypeOf((*MockTorrentCommandService)(nil).DropReadiness), hash)
}

// EnqueueMetadataFinalize mocks base method.
func (m *MockTorrentCommandService) EnqueueMetadataFinalize(tor contracts.TorrentHandle, spec *contracts.TorrentSpec, saveToDB bool) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueMetadataFinalize", tor, spec, saveToDB)
	ret0, _ := ret[0].(bool)
	return ret0
}

// EnqueueMetadataFinalize indicates an expected call of EnqueueMetadataFinalize.
func (mr *MockTorrentCommandServiceMockRecorder) EnqueueMetadataFinalize(tor, spec, saveToDB any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueMetadataFinalize", reflect.TypeOf((*MockTorrentCommandService)(nil).EnqueueMetadataFinalize), tor, spec, saveToDB)
}

// EnqueuePreload mocks base method.
func (m *MockTorrentCommandService) EnqueuePreload(tor contracts.TorrentHandle, index int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueuePreload", tor, index)
	ret0, _ := ret[0].(bool)
	return ret0
}

// EnqueuePreload indicates an expected call of EnqueuePreload.
func (mr *MockTorrentCommandServiceMockRecorder) EnqueuePreload(tor, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueuePreload", reflect.TypeOf((*MockTorrentCommandService)(nil).EnqueuePreload), tor, index)
}

// Remove mocks base method.
func (m *MockTorrentCommandService) Remove(hash string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Remove", hash)
}

// Remove indicates an expected call of Remove.
func (mr *MockTorrentCommandServiceMockRecorder) Remove(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockTorrentCommandService)(nil).Remove), hash)
}

// SaveToDB mocks base method.
func (m *MockTorrentCommandService) SaveToDB(tor contracts.TorrentHandle) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveToDB", tor)
}

// SaveToDB indicates an expected call of SaveToDB.
func (mr *MockTorrentCommandServiceMockRecorder) SaveToDB(tor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToDB", reflect.TypeOf((*MockTorrentCommandService)(nil).SaveToDB), tor)
}

// Set mocks base method.
func (m *MockTorrentCommandService) Set(hash, title, poster, category, data string) contracts.TorrentHandle {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", hash, title, poster, category, data)
	ret0, _ := ret[0].(contracts.TorrentHandle)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockTorrentCommandServiceMockRecorder) Set(hash, title, poster, category, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockTorrentCommandService)(nil).Set), hash, title, poster, category, data)
}

// MockTorrentStreamService is a mock of TorrentStreamService interface.
type MockTorrentStreamService struct {
	ctrl     *gomock.Controller
	recorder *MockTorrentStreamServiceMockRecorder
	isgomock struct{}
}

// MockTorrentStreamServiceMockRecorder is the mock recorder for MockTorrentStreamService.
type MockTorrentStreamServiceMockRecorder struct {
	mock *MockTorrentStreamService
}

// NewMockTorrentStreamService creates a new mock instance.
func NewMockTorrentStreamService(ctrl *gomock.Controller) *MockTorrentStreamService {
	mock := &MockTorrentStreamService{ctrl: ctrl}
	mock.recorder = &MockTorrentStreamServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTorrentStreamService) EXPECT() *MockTorrentStreamServiceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockTorrentStreamService) Add(spec contracts.TorrentSpec, title, poster, data, category string) (contracts.TorrentHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", spec, title, poster, data, category)
	ret0, _ := ret[0].(contracts.TorrentHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockTorrentStreamServiceMockRecorder) Add(spec, title, poster, data, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockTorrentStreamService)(nil).Add), spec, title, poster, data, category)
}

// Get mocks base method.
func (m *MockTorrentStreamService) Get(hash string) contracts.TorrentHandle {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", hash)
	ret0, _ := ret[0].(contracts.TorrentHandle)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockTorrentStreamServiceMockRecorder) Get(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTorrentStreamService)(nil).Get), hash)
}

// IsStored mocks base method.
func (m *MockTorrentStreamService) IsStored(tor contracts.TorrentHandle) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsStored", tor)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsStored indicates an expected call of IsStored.
func (mr *MockTorrentStreamServiceMockRecorder) IsStored(tor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsStored", reflect.TypeOf((*MockTorrentStreamService)(nil).IsStored), tor)
}

// LoadFromDB mocks base method.
func (m *MockTorrentStreamService) LoadFromDB(tor contracts.TorrentHandle) contracts.TorrentHandle {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadFromDB", tor)
	ret0, _ := ret[0].(contracts.TorrentHandle)
	return ret0
}

// LoadFromDB indicates an expected call of LoadFromDB.
func (mr *MockTorrentStreamServiceMockRecorder) LoadFromDB(tor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadFromDB", reflect.TypeOf((*MockTorrentStreamService)(nil).LoadFromDB), tor)
}

// Status mocks base method.
func (m *MockTorrentStreamService) Status(tor contracts.TorrentHandle) *state.TorrentStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", tor)
	ret0, _ := ret[0].(*state.TorrentStatus)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockTorrentStreamServiceMockRecorder) Status(tor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockTorrentStreamService)(nil).Status), tor)
}

// StatusByHash mocks base method.
func (m *MockTorrentStreamService) StatusByHash(hash string) (*state.TorrentStatus, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatusByHash", hash)
	ret0, _ := ret[0].(*state.TorrentStatus)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// StatusByHash indicates an expected call of StatusByHash.
func (mr *MockTorrentStreamServiceMockRecorder) StatusByHash(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatusByHash", reflect.TypeOf((*MockTorrentStreamService)(nil).StatusByHash), hash)
}

// MockTorrentStreamActions is a mock of TorrentStreamActions interface.
type MockTorrentStreamActions struct {
	ctrl     *gomock.Controller
	recorder *MockTorrentStreamActionsMockRecorder
	isgomock struct{}
}

// MockTorrentStreamActionsMockRecorder is the mock recorder for MockTorrentStreamActions.
type MockTorrentStreamActionsMockRecorder struct {
	mock *MockTorrentStreamActions
}

// NewMockTorrentStreamActions creates a new mock instance.
func NewMockTorrentStreamActions(ctrl *gomock.Controller) *MockTorrentStreamActions {
	mock := &MockTorrentStreamActions{ctrl: ctrl}
	mock.recorder = &MockTorrentStreamActionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTorrentStreamActions) EXPECT() *MockTorrentStreamActionsMockRecorder {
	return m.recorder
}

// EnqueuePreload mocks base method.
func (m *MockTorrentStreamActions) EnqueuePreload(tor contracts.TorrentHandle, index int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueuePreload", tor, index)
	ret0, _ := ret[0].(bool)
	return ret0
}

// EnqueuePreload indicates an expected call of EnqueuePreload.
func (mr *MockTorrentStreamActionsMockRecorder) EnqueuePreload(tor, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueuePreload", reflect.TypeOf((*MockTorrentStreamActions)(nil).EnqueuePreload), tor, index)
}

// SaveToDB mocks base method.
func (m *MockTorrentStreamActions) SaveToDB(tor contracts.TorrentHandle) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveToDB", tor)
}

// SaveToDB indicates an expected call of SaveToDB.
func (mr *MockTorrentStreamActionsMockRecorder) SaveToDB(tor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToDB", reflect.TypeOf((*MockTorrentStreamActions)(nil).SaveToDB), tor)
}

// MockTorrentPlaylistService is a mock of TorrentPlaylistService interface.
type MockTorrentPlaylistService struct {
	ctrl     *gomock.Controller
	recorder *MockTorrentPlaylistServiceMockRecorder
	isgomock struct{}
}

// MockTorrentPlaylistServiceMockRecorder is the mock recorder for MockTorrentPlaylistService.
type MockTorrentPlaylistServiceMockRecorder struct {
	mock *MockTorrentPlaylistService
}

// NewMockTorrentPlaylistService creates a new mock instance.
func NewMockTorrentPlaylistService(ctrl *gomock.Controller) *MockTorrentPlaylistService {
	mock := &MockTorrentPlaylistService{ctrl: ctrl}
	mock.recorder = &MockTorrentPlaylistServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTorrentPlaylistService) EXPECT() *MockTorrentPlaylistServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockTorrentPlaylistService) Get(hash string) contracts.TorrentHandle {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", hash)
	ret0, _ := ret[0].(contracts.TorrentHandle)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockTorrentPlaylistServiceMockRecorder) Get(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTorrentPlaylistService)(nil).Get), hash)
}

// IsStored mocks base method.
func (m *MockTorrentPlaylistService) IsStored(tor contracts.TorrentHandle) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsStored", tor)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsStored indicates an expected call of IsStored.
func (mr *MockTorrentPlaylistServiceMockRecorder) IsStored(tor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsStored", reflect.TypeOf((*MockTorrentPlaylistService)(nil).IsStored), tor)
}

// List mocks base method.
func (m *MockTorrentPlaylistService) List() []contracts.TorrentHandle {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]contracts.TorrentHandle)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockTorrentPlaylistServiceMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTorrentPlaylistService)(nil).List))
}

// ListHashes mocks base method.
func (m *MockTorrentPlaylistService) ListHashes() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHashes")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ListHashes indicates an expected call of ListHashes.
func (mr *MockTorrentPlaylistServiceMockRecorder) ListHashes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHashes", reflect.TypeOf((*MockTorrentPlaylistService)(nil).ListHashes))
}

// LoadFromDB mocks base method.
func (m *MockTorrentPlaylistService) LoadFromDB(tor contracts.TorrentHandle) contracts.TorrentHandle {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadFromDB", tor)
	ret0, _ := ret[0].(contracts.TorrentHandle)
	return ret0
}

// LoadFromDB indicates an expected call of LoadFromDB.
func (mr *MockTorrentPlaylistServiceMockRecorder) LoadFromDB(tor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadFromDB", reflect.TypeOf((*MockTorrentPlaylistService)(nil).LoadFromDB), tor)
}

// Status mocks base method.
func (m *MockTorrentPlaylistService) Status(tor contracts.TorrentHandle) *state.TorrentStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", tor)
	ret0, _ := ret[0].(*state.TorrentStatus)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockTorrentPlaylistServiceMockRecorder) Status(tor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockTorrentPlaylistService)(nil).Status), tor)
}

// StatusByHash mocks base method.
func (m *MockTorrentPlaylistService) StatusByHash(hash string) (*state.TorrentStatus, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatusByHash", hash)
	ret0, _ := ret[0].(*state.TorrentStatus)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// StatusByHash indicates an expected call of StatusByHash.
func (mr *MockTorrentPlaylistServiceMockRecorder) StatusByHash(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatusByHash", reflect.TypeOf((*MockTorrentPlaylistService)(nil).StatusByHash), hash)
}

// Statuses mocks base method.
func (m *MockTorrentPlaylistService) Statuses() []*state.TorrentStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Statuses")
	ret0, _ := ret[0].([]*state.TorrentStatus)
	return ret0
}

// Statuses indicates an expected call of Statuses.
func (mr *MockTorrentPlaylistServiceMockRecorder) Statuses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Statuses", reflect.TypeOf((*MockTorrentPlaylistService)(nil).Statuses))
}

// MockTorrentPlayService is a mock of TorrentPlayService interface.
type MockTorrentPlayService struct {
	ctrl     *gomock.Controller
	recorder *MockTorrentPlayServiceMockRecorder
	isgomock struct{}
}

// MockTorrentPlayServiceMockRecorder is the mock recorder for MockTorrentPlayService.
type MockTorrentPlayServiceMockRecorder struct {
	mock *MockTorrentPlayService
}

// NewMockTorrentPlayService creates a new mock instance.
func NewMockTorrentPlayService(ctrl *gomock.Controller) *MockTorrentPlayService {
	mock := &MockTorrentPlayService{ctrl: ctrl}
	mock.recorder = &MockTorrentPlayServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTorrentPlayService) EXPECT() *MockTorrentPlayServiceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockTorrentPlayService) Add(spec contracts.TorrentSpec, title, poster, data, category string) (contracts.TorrentHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", spec, title, poster, data, category)
	ret0, _ := ret[0].(contracts.TorrentHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockTorrentPlayServiceMockRecorder) Add(spec, title, poster, data, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockTorrentPlayService)(nil).Add), spec, title, poster, data, category)
}

// Get mocks base method.
func (m *MockTorrentPlayService) Get(hash string) contracts.TorrentHandle {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", hash)
	ret0, _ := ret[0].(contracts.TorrentHandle)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockTorrentPlayServiceMockRecorder) Get(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTorrentPlayService)(nil).Get), hash)
}

// IsStored mocks base method.
func (m *MockTorrentPlayService) IsStored(tor contracts.TorrentHandle) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsStored", tor)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsStored indicates an expected call of IsStored.
func (mr *MockTorrentPlayServiceMockRecorder) IsStored(tor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsStored", reflect.TypeOf((*MockTorrentPlayService)(nil).IsStored), tor)
}

// Status mocks base method.
func (m *MockTorrentPlayService) Status(tor contracts.TorrentHandle) *state.TorrentStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", tor)
	ret0, _ := ret[0].(*state.TorrentStatus)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockTorrentPlayServiceMockRecorder) Status(tor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockTorrentPlayService)(nil).Status), tor)
}

// StatusByHash mocks base method.
func (m *MockTorrentPlayService) StatusByHash(hash string) (*state.TorrentStatus, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatusByHash", hash)
	ret0, _ := ret[0].(*state.TorrentStatus)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// StatusByHash indicates an expected call of StatusByHash.
func (mr *MockTorrentPlayServiceMockRecorder) StatusByHash(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatusByHash", reflect.TypeOf((*MockTorrentPlayService)(nil).StatusByHash), hash)
}

// MockAPITorrentService is a mock of TorrentService interface.
type MockAPITorrentService struct {
	ctrl     *gomock.Controller
	recorder *MockAPITorrentServiceMockRecorder
	isgomock struct{}
}

// MockAPITorrentServiceMockRecorder is the mock recorder for MockAPITorrentService.
type MockAPITorrentServiceMockRecorder struct {
	mock *MockAPITorrentService
}

// NewMockAPITorrentService creates a new mock instance.
func NewMockAPITorrentService(ctrl *gomock.Controller) *MockAPITorrentService {
	mock := &MockAPITorrentService{ctrl: ctrl}
	mock.recorder = &MockAPITorrentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPITorrentService) EXPECT() *MockAPITorrentServiceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockAPITorrentService) Add(spec contracts.TorrentSpec, title, poster, data, category string) (contracts.TorrentHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", spec, title, poster, data, category)
	ret0, _ := ret[0].(contracts.TorrentHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockAPITorrentServiceMockRecorder) Add(spec, title, poster, data, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockAPITorrentService)(nil).Add), spec, title, poster, data, category)
}

// CacheStateByHash mocks base method.
func (m *MockAPITorrentService) CacheStateByHash(hash string) (any, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CacheStateByHash", hash)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// CacheStateByHash indicates an expected call of CacheStateByHash.
func (mr *MockAPITorrentServiceMockRecorder) CacheStateByHash(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheStateByHash", reflect.TypeOf((*MockAPITorrentService)(nil).CacheStateByHash), hash)
}

// Drop mocks base method.
func (m *MockAPITorrentService) Drop(hash string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Drop", hash)
}

// Drop indicates an expected call of Drop.
func (mr *MockAPITorrentServiceMockRecorder) Drop(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Drop", reflect.TypeOf((*MockAPITorrentService)(nil).Drop), hash)
}

// DropReadiness mocks base method.
func (m *MockAPITorrentService) DropReadiness(hash string) contracts.DropReadiness {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DropReadiness", hash)
	ret0, _ := ret[0].(contracts.DropReadiness)
	return ret0
}

// DropReadiness indicates an expected call of DropReadiness.
func (mr *MockAPITorrentServiceMockRecorder) DropReadiness(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropReadiness", reflect.TypeOf((*MockAPITorrentService)(nil).DropReadiness), hash)
}

// EnqueueMetadataFinalize mocks base method.
func (m *MockAPITorrentService) EnqueueMetadataFinalize(tor contracts.TorrentHandle, spec *contracts.TorrentSpec, saveToDB bool) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueMetadataFinalize", tor, spec, saveToDB)
	ret0, _ := ret[0].(bool)
	return ret0
}

// EnqueueMetadataFinalize indicates an expected call of EnqueueMetadataFinalize.
func (mr *MockAPITorrentServiceMockRecorder) EnqueueMetadataFinalize(tor, spec, saveToDB any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueMetadataFinalize", reflect.TypeOf((*MockAPITorrentService)(nil).EnqueueMetadataFinalize), tor, spec, saveToDB)
}

// EnqueuePreload mocks base method.
func (m *MockAPITorrentService) EnqueuePreload(tor contracts.TorrentHandle, index int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueuePreload", tor, index)
	ret0, _ := ret[0].(bool)
	return ret0
}

// EnqueuePreload indicates an expected call of EnqueuePreload.
func (mr *MockAPITorrentServiceMockRecorder) EnqueuePreload(tor, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueuePreload", reflect.TypeOf((*MockAPITorrentService)(nil).EnqueuePreload), tor, index)
}

// Get mocks base method.
func (m *MockAPITorrentService) Get(hash string) contracts.TorrentHandle {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", hash)
	ret0, _ := ret[0].(contracts.TorrentHandle)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockAPITorrentServiceMockRecorder) Get(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAPITorrentService)(nil).Get), hash)
}

// IsStored mocks base method.
func (m *MockAPITorrentService) IsStored(tor contracts.TorrentHandle) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsStored", tor)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsStored indicates an expected call of IsStored.
func (mr *MockAPITorrentServiceMockRecorder) IsStored(tor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsStored", reflect.TypeOf((*MockAPITorrentService)(nil).IsStored), tor)
}

// List mocks base method.
func (m *MockAPITorrentService) List() []contracts.TorrentHandle {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]contracts.TorrentHandle)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockAPITorrentServiceMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAPITorrentService)(nil).List))
}

// ListHashes mocks base method.
func (m *MockAPITorrentService) ListHashes() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHashes")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ListHashes indicates an expected call of ListHashes.
func (mr *MockAPITorrentServiceMockRecorder) ListHashes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHashes", reflect.TypeOf((*MockAPITorrentService)(nil).ListHashes))
}

// LoadFromDB mocks base method.
func (m *MockAPITorrentService) LoadFromDB(tor contracts.TorrentHandle) contracts.TorrentHandle {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadFromDB", tor)
	ret0, _ := ret[0].(contracts.TorrentHandle)
	return ret0
}

// LoadFromDB indicates an expected call of LoadFromDB.
func (mr *MockAPITorrentServiceMockRecorder) LoadFromDB(tor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadFromDB", reflect.TypeOf((*MockAPITorrentService)(nil).LoadFromDB), tor)
}

// Remove mocks base method.
func (m *MockAPITorrentService) Remove(hash string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Remove", hash)
}

// Remove indicates an expected call of Remove.
func (mr *MockAPITorrentServiceMockRecorder) Remove(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockAPITorrentService)(nil).Remove), hash)
}

// SaveToDB mocks base method.
func (m *MockAPITorrentService) SaveToDB(tor contracts.TorrentHandle) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveToDB", tor)
}

// SaveToDB indicates an expected call of SaveToDB.
func (mr *MockAPITorrentServiceMockRecorder) SaveToDB(tor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToDB", reflect.TypeOf((*MockAPITorrentService)(nil).SaveToDB), tor)
}

// Set mocks base method.
func (m *MockAPITorrentService) Set(hash, title, poster, category, data string) contracts.TorrentHandle {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", hash, title, poster, category, data)
	ret0, _ := ret[0].(contracts.TorrentHandle)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockAPITorrentServiceMockRecorder) Set(hash, title, poster, category, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockAPITorrentService)(nil).Set), hash, title, poster, category, data)
}

// Status mocks base method.
func (m *MockAPITorrentService) Status(tor contracts.TorrentHandle) *state.TorrentStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", tor)
	ret0, _ := ret[0].(*state.TorrentStatus)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockAPITorrentServiceMockRecorder) Status(tor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockAPITorrentService)(nil).Status), tor)
}

// StatusByHash mocks base method.
func (m *MockAPITorrentService) StatusByHash(hash string) (*state.TorrentStatus, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatusByHash", hash)
	ret0, _ := ret[0].(*state.TorrentStatus)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// StatusByHash indicates an expected call of StatusByHash.
func (mr *MockAPITorrentServiceMockRecorder) StatusByHash(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatusByHash", reflect.TypeOf((*MockAPITorrentService)(nil).StatusByHash), hash)
}

// Statuses mocks base method.
func (m *MockAPITorrentService) Statuses() []*state.TorrentStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Statuses")
	ret0, _ := ret[0].([]*state.TorrentStatus)
	return ret0
}

// Statuses indicates an expected call of Statuses.
func (mr *MockAPITorrentServiceMockRecorder) Statuses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Statuses", reflect.TypeOf((*MockAPITorrentService)(nil).Statuses))
}

// MockAPISettingsService is a mock of SettingsService interface.
type MockAPISettingsService struct {
	ctrl     *gomock.Controller
	recorder *MockAPISettingsServiceMockRecorder
	isgomock struct{}
}

// MockAPISettingsServiceMockRecorder is the mock recorder for MockAPISettingsService.
type MockAPISettingsServiceMockRecorder struct {
	mock *MockAPISettingsService
}

// NewMockAPISettingsService creates a new mock instance.
func NewMockAPISettingsService(ctrl *gomock.Controller) *MockAPISettingsService {
	mock := &MockAPISettingsService{ctrl: ctrl}
	mock.recorder = &MockAPISettingsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPISettingsService) EXPECT() *MockAPISettingsServiceMockRecorder {
	return m.recorder
}

// BuildPlayURL mocks base method.
func (m *MockAPISettingsService) BuildPlayURL(hash, fileID string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildPlayURL", hash, fileID)
	ret0, _ := ret[0].(string)
	return ret0
}

// BuildPlayURL indicates an expected call of BuildPlayURL.
func (mr *MockAPISettingsServiceMockRecorder) BuildPlayURL(hash, fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildPlayURL", reflect.TypeOf((*MockAPISettingsService)(nil).BuildPlayURL), hash, fileID)
}

// Current mocks base method.
func (m *MockAPISettingsService) Current() *settings.BTSets {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Current")
	ret0, _ := ret[0].(*settings.BTSets)
	return ret0
}

// Current indicates an expected call of Current.
func (mr *MockAPISettingsServiceMockRecorder) Current() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Current", reflect.TypeOf((*MockAPISettingsService)(nil).Current))
}

// EnableDLNA mocks base method.
func (m *MockAPISettingsService) EnableDLNA() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableDLNA")
	ret0, _ := ret[0].(bool)
	return ret0
}

// EnableDLNA indicates an expected call of EnableDLNA.
func (mr *MockAPISettingsServiceMockRecorder) EnableDLNA() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableDLNA", reflect.TypeOf((*MockAPISettingsService)(nil).EnableDLNA))
}

// EnableDebug mocks base method.
func (m *MockAPISettingsService) EnableDebug() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableDebug")
	ret0, _ := ret[0].(bool)
	return ret0
}

// EnableDebug indicates an expected call of EnableDebug.
func (mr *MockAPISettingsServiceMockRecorder) EnableDebug() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableDebug", reflect.TypeOf((*MockAPISettingsService)(nil).EnableDebug))
}

// GetStoragePreferences mocks base method.
func (m *MockAPISettingsService) GetStoragePreferences() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoragePreferences")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// GetStoragePreferences indicates an expected call of GetStoragePreferences.
func (mr *MockAPISettingsServiceMockRecorder) GetStoragePreferences() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoragePreferences", reflect.TypeOf((*MockAPISettingsService)(nil).GetStoragePreferences))
}

// ReadOnly mocks base method.
func (m *MockAPISettingsService) ReadOnly() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadOnly")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ReadOnly indicates an expected call of ReadOnly.
func (mr *MockAPISettingsServiceMockRecorder) ReadOnly() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadOnly", reflect.TypeOf((*MockAPISettingsService)(nil).ReadOnly))
}

// Set mocks base method.
func (m *MockAPISettingsService) Set(arg0 *settings.BTSets) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", arg0)
}

// Set indicates an expected call of Set.
func (mr *MockAPISettingsServiceMockRecorder) Set(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockAPISettingsService)(nil).Set), arg0)
}

// SetDefault mocks base method.
func (m *MockAPISettingsService) SetDefault() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDefault")
}

// SetDefault indicates an expected call of SetDefault.
func (mr *MockAPISettingsServiceMockRecorder) SetDefault() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefault", reflect.TypeOf((*MockAPISettingsService)(nil).SetDefault))
}

// SetStoragePreferences mocks base method.
func (m *MockAPISettingsService) SetStoragePreferences(arg0 map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStoragePreferences", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStoragePreferences indicates an expected call of SetStoragePreferences.
func (mr *MockAPISettingsServiceMockRecorder) SetStoragePreferences(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStoragePreferences", reflect.TypeOf((*MockAPISettingsService)(nil).SetStoragePreferences), arg0)
}

// TMDBConfig mocks base method.
func (m *MockAPISettingsService) TMDBConfig() (settings.TMDBConfig, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TMDBConfig")
	ret0, _ := ret[0].(settings.TMDBConfig)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// TMDBConfig indicates an expected call of TMDBConfig.
func (mr *MockAPISettingsServiceMockRecorder) TMDBConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TMDBConfig", reflect.TypeOf((*MockAPISettingsService)(nil).TMDBConfig))
}

// MockAPIViewedService is a mock of ViewedService interface.
type MockAPIViewedService struct {
	ctrl     *gomock.Controller
	recorder *MockAPIViewedServiceMockRecorder
	isgomock struct{}
}

// MockAPIViewedServiceMockRecorder is the mock recorder for MockAPIViewedService.
type MockAPIViewedServiceMockRecorder struct {
	mock *MockAPIViewedService
}

// NewMockAPIViewedService creates a new mock instance.
func NewMockAPIViewedService(ctrl *gomock.Controller) *MockAPIViewedService {
	mock := &MockAPIViewedService{ctrl: ctrl}
	mock.recorder = &MockAPIViewedServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIViewedService) EXPECT() *MockAPIViewedServiceMockRecorder {
	return m.recorder
}

// ListViewed mocks base method.
func (m *MockAPIViewedService) ListViewed(hash string) []*settings.Viewed {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListViewed", hash)
	ret0, _ := ret[0].([]*settings.Viewed)
	return ret0
}

// ListViewed indicates an expected call of ListViewed.
func (mr *MockAPIViewedServiceMockRecorder) ListViewed(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListViewed", reflect.TypeOf((*MockAPIViewedService)(nil).ListViewed), hash)
}

// RemoveViewed mocks base method.
func (m *MockAPIViewedService) RemoveViewed(v *settings.Viewed) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveViewed", v)
}

// RemoveViewed indicates an expected call of RemoveViewed.
func (mr *MockAPIViewedServiceMockRecorder) RemoveViewed(v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveViewed", reflect.TypeOf((*MockAPIViewedService)(nil).RemoveViewed), v)
}

// SetViewed mocks base method.
func (m *MockAPIViewedService) SetViewed(v *settings.Viewed) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetViewed", v)
}

// SetViewed indicates an expected call of SetViewed.
func (mr *MockAPIViewedServiceMockRecorder) SetViewed(v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetViewed", reflect.TypeOf((*MockAPIViewedService)(nil).SetViewed), v)
}

// MockAPISystemService is a mock of SystemService interface.
type MockAPISystemService struct {
	ctrl     *gomock.Controller
	recorder *MockAPISystemServiceMockRecorder
	isgomock struct{}
}

// MockAPISystemServiceMockRecorder is the mock recorder for MockAPISystemService.
type MockAPISystemServiceMockRecorder struct {
	mock *MockAPISystemService
}

// NewMockAPISystemService creates a new mock instance.
func NewMockAPISystemService(ctrl *gomock.Controller) *MockAPISystemService {
	mock := &MockAPISystemService{ctrl: ctrl}
	mock.recorder = &MockAPISystemServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPISystemService) EXPECT() *MockAPISystemServiceMockRecorder {
	return m.recorder
}

// Shutdown mocks base method.
func (m *MockAPISystemService) Shutdown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown")
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockAPISystemServiceMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockAPISystemService)(nil).Shutdown))
}

// MockAPISearchService is a mock of SearchService interface.
type MockAPISearchService struct {
	ctrl     *gomock.Controller
	recorder *MockAPISearchServiceMockRecorder
	isgomock struct{}
}

// MockAPISearchServiceMockRecorder is the mock recorder for MockAPISearchService.
type MockAPISearchServiceMockRecorder struct {
	mock *MockAPISearchService
}

// NewMockAPISearchService creates a new mock instance.
func NewMockAPISearchService(ctrl *gomock.Controller) *MockAPISearchService {
	mock := &MockAPISearchService{ctrl: ctrl}
	mock.recorder = &MockAPISearchServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPISearchService) EXPECT() *MockAPISearchServiceMockRecorder {
	return m.recorder
}

// EnableTorznabSearch mocks base method.
func (m *MockAPISearchService) EnableTorznabSearch() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableTorznabSearch")
	ret0, _ := ret[0].(bool)
	return ret0
}

// EnableTorznabSearch indicates an expected call of EnableTorznabSearch.
func (mr *MockAPISearchServiceMockRecorder) EnableTorznabSearch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableTorznabSearch", reflect.TypeOf((*MockAPISearchService)(nil).EnableTorznabSearch))
}

// TorznabSearch mocks base method.
func (m *MockAPISearchService) TorznabSearch(query string, index int) []*contracts.SearchResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TorznabSearch", query, index)
	ret0, _ := ret[0].([]*contracts.SearchResult)
	return ret0
}

// TorznabSearch indicates an expected call of TorznabSearch.
func (mr *MockAPISearchServiceMockRecorder) TorznabSearch(query, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TorznabSearch", reflect.TypeOf((*MockAPISearchService)(nil).TorznabSearch), query, index)
}

// TorznabTest mocks base method.
func (m *MockAPISearchService) TorznabTest(host, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TorznabTest", host, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// TorznabTest indicates an expected call of TorznabTest.
func (mr *MockAPISearchServiceMockRecorder) TorznabTest(host, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TorznabTest", reflect.TypeOf((*MockAPISearchService)(nil).TorznabTest), host, key)
}

// MockAPIMediaService is a mock of MediaService interface.
type MockAPIMediaService struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMediaServiceMockRecorder
	isgomock struct{}
}

// MockAPIMediaServiceMockRecorder is the mock recorder for MockAPIMediaService.
type MockAPIMediaServiceMockRecorder struct {
	mock *MockAPIMediaService
}

// NewMockAPIMediaService creates a new mock instance.
func NewMockAPIMediaService(ctrl *gomock.Controller) *MockAPIMediaService {
	mock := &MockAPIMediaService{ctrl: ctrl}
	mock.recorder = &MockAPIMediaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIMediaService) EXPECT() *MockAPIMediaServiceMockRecorder {
	return m.recorder
}

// ProbePlayURL mocks base method.
func (m *MockAPIMediaService) ProbePlayURL(hash, fileID string) (*ffprobe.ProbeData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProbePlayURL", hash, fileID)
	ret0, _ := ret[0].(*ffprobe.ProbeData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProbePlayURL indicates an expected call of ProbePlayURL.
func (mr *MockAPIMediaServiceMockRecorder) ProbePlayURL(hash, fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProbePlayURL", reflect.TypeOf((*MockAPIMediaService)(nil).ProbePlayURL), hash, fileID)
}

// MockAPIModulesService is a mock of ModulesService interface.
type MockAPIModulesService struct {
	ctrl     *gomock.Controller
	recorder *MockAPIModulesServiceMockRecorder
	isgomock struct{}
}

// MockAPIModulesServiceMockRecorder is the mock recorder for MockAPIModulesService.
type MockAPIModulesServiceMockRecorder struct {
	mock *MockAPIModulesService
}

// NewMockAPIModulesService creates a new mock instance.
func NewMockAPIModulesService(ctrl *gomock.Controller) *MockAPIModulesService {
	mock := &MockAPIModulesService{ctrl: ctrl}
	mock.recorder = &MockAPIModulesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIModulesService) EXPECT() *MockAPIModulesServiceMockRecorder {
	return m.recorder
}

// RestartDLNA mocks base method.
func (m *MockAPIModulesService) RestartDLNA(enable bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestartDLNA", enable)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestartDLNA indicates an expected call of RestartDLNA.
func (mr *MockAPIModulesServiceMockRecorder) RestartDLNA(enable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestartDLNA", reflect.TypeOf((*MockAPIModulesService)(nil).RestartDLNA), enable)
}

// StopDLNA mocks base method.
func (m *MockAPIModulesService) StopDLNA() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopDLNA")
}

// StopDLNA indicates an expected call of StopDLNA.
func (mr *MockAPIModulesServiceMockRecorder) StopDLNA() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopDLNA", reflect.TypeOf((*MockAPIModulesService)(nil).StopDLNA))
}

// MockTorrentParserService is a mock of TorrentParserService interface.
type MockTorrentParserService struct {
	ctrl     *gomock.Controller
	recorder *MockTorrentParserServiceMockRecorder
	isgomock struct{}
}

// MockTorrentParserServiceMockRecorder is the mock recorder for MockTorrentParserService.
type MockTorrentParserServiceMockRecorder struct {
	mock *MockTorrentParserService
}

// NewMockTorrentParserService creates a new mock instance.
func NewMockTorrentParserService(ctrl *gomock.Controller) *MockTorrentParserService {
	mock := &MockTorrentParserService{ctrl: ctrl}
	mock.recorder = &MockTorrentParserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTorrentParserService) EXPECT() *MockTorrentParserServiceMockRecorder {
	return m.recorder
}

// ParseLink mocks base method.
func (m *MockTorrentParserService) ParseLink(link, title, poster, category string) (contracts.TorrentSpec, contracts.StreamMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseLink", link, title, poster, category)
	ret0, _ := ret[0].(contracts.TorrentSpec)
	ret1, _ := ret[1].(contracts.StreamMeta)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ParseLink indicates an expected call of ParseLink.
func (mr *MockTorrentParserServiceMockRecorder) ParseLink(link, title, poster, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseLink", reflect.TypeOf((*MockTorrentParserService)(nil).ParseLink), link, title, poster, category)
}

// ParseTorrentFile mocks base method.
func (m *MockTorrentParserService) ParseTorrentFile(reader io.Reader) (contracts.TorrentSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseTorrentFile", reader)
	ret0, _ := ret[0].(contracts.TorrentSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseTorrentFile indicates an expected call of ParseTorrentFile.
func (mr *MockTorrentParserServiceMockRecorder) ParseTorrentFile(reader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseTorrentFile", reflect.TypeOf((*MockTorrentParserService)(nil).ParseTorrentFile), reader)
}

// MockStreamOrchestratorService is a mock of StreamOrchestratorService interface.
type MockStreamOrchestratorService struct {
	ctrl     *gomock.Controller
	recorder *MockStreamOrchestratorServiceMockRecorder
	isgomock struct{}
}

// MockStreamOrchestratorServiceMockRecorder is the mock recorder for MockStreamOrchestratorService.
type MockStreamOrchestratorServiceMockRecorder struct {
	mock *MockStreamOrchestratorService
}

// NewMockStreamOrchestratorService creates a new mock instance.
func NewMockStreamOrchestratorService(ctrl *gomock.Controller) *MockStreamOrchestratorService {
	mock := &MockStreamOrchestratorService{ctrl: ctrl}
	mock.recorder = &MockStreamOrchestratorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamOrchestratorService) EXPECT() *MockStreamOrchestratorServiceMockRecorder {
	return m.recorder
}

// EnsureTorrent mocks base method.
func (m *MockStreamOrchestratorService) EnsureTorrent(torrents contracts.TorrentStreamService, spec contracts.TorrentSpec, meta contracts.StreamMeta, allowCreate bool) (contracts.TorrentHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureTorrent", torrents, spec, meta, allowCreate)
	ret0, _ := ret[0].(contracts.TorrentHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureTorrent indicates an expected call of EnsureTorrent.
func (mr *MockStreamOrchestratorServiceMockRecorder) EnsureTorrent(torrents, spec, meta, allowCreate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureTorrent", reflect.TypeOf((*MockStreamOrchestratorService)(nil).EnsureTorrent), torrents, spec, meta, allowCreate)
}

// MockStreamHelperService is a mock of StreamHelperService interface.
type MockStreamHelperService struct {
	ctrl     *gomock.Controller
	recorder *MockStreamHelperServiceMockRecorder
	isgomock struct{}
}

// MockStreamHelperServiceMockRecorder is the mock recorder for MockStreamHelperService.
type MockStreamHelperServiceMockRecorder struct {
	mock *MockStreamHelperService
}

// NewMockStreamHelperService creates a new mock instance.
func NewMockStreamHelperService(ctrl *gomock.Controller) *MockStreamHelperService {
	mock := &MockStreamHelperService{ctrl: ctrl}
	mock.recorder = &MockStreamHelperServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamHelperService) EXPECT() *MockStreamHelperServiceMockRecorder {
	return m.recorder
}

// NormalizePlaylistName mocks base method.
func (m *MockStreamHelperService) NormalizePlaylistName(rawName, fallback string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NormalizePlaylistName", rawName, fallback)
	ret0, _ := ret[0].(string)
	return ret0
}

// NormalizePlaylistName indicates an expected call of NormalizePlaylistName.
func (mr *MockStreamHelperServiceMockRecorder) NormalizePlaylistName(rawName, fallback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NormalizePlaylistName", reflect.TypeOf((*MockStreamHelperService)(nil).NormalizePlaylistName), rawName, fallback)
}

// ParseFileIndex mocks base method.
func (m *MockStreamHelperService) ParseFileIndex(index string, fileCount int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseFileIndex", index, fileCount)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseFileIndex indicates an expected call of ParseFileIndex.
func (mr *MockStreamHelperServiceMockRecorder) ParseFileIndex(index, fileCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseFileIndex", reflect.TypeOf((*MockStreamHelperService)(nil).ParseFileIndex), index, fileCount)
}

// MockAPIStreamService is a mock of StreamService interface.
type MockAPIStreamService struct {
	ctrl     *gomock.Controller
	recorder *MockAPIStreamServiceMockRecorder
	isgomock struct{}
}

// MockAPIStreamServiceMockRecorder is the mock recorder for MockAPIStreamService.
type MockAPIStreamServiceMockRecorder struct {
	mock *MockAPIStreamService
}

// NewMockAPIStreamService creates a new mock instance.
func NewMockAPIStreamService(ctrl *gomock.Controller) *MockAPIStreamService {
	mock := &MockAPIStreamService{ctrl: ctrl}
	mock.recorder = &MockAPIStreamServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIStreamService) EXPECT() *MockAPIStreamServiceMockRecorder {
	return m.recorder
}

// EnsureTorrent mocks base method.
func (m *MockAPIStreamService) EnsureTorrent(torrents contracts.TorrentStreamService, spec contracts.TorrentSpec, meta contracts.StreamMeta, allowCreate bool) (contracts.TorrentHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureTorrent", torrents, spec, meta, allowCreate)
	ret0, _ := ret[0].(contracts.TorrentHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureTorrent indicates an expected call of EnsureTorrent.
func (mr *MockAPIStreamServiceMockRecorder) EnsureTorrent(torrents, spec, meta, allowCreate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureTorrent", reflect.TypeOf((*MockAPIStreamService)(nil).EnsureTorrent), torrents, spec, meta, allowCreate)
}

// NormalizePlaylistName mocks base method.
func (m *MockAPIStreamService) NormalizePlaylistName(rawName, fallback string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NormalizePlaylistName", rawName, fallback)
	ret0, _ := ret[0].(string)
	return ret0
}

// NormalizePlaylistName indicates an expected call of NormalizePlaylistName.
func (mr *MockAPIStreamServiceMockRecorder) NormalizePlaylistName(rawName, fallback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NormalizePlaylistName", reflect.TypeOf((*MockAPIStreamService)(nil).NormalizePlaylistName), rawName, fallback)
}

// ParseFileIndex mocks base method.
func (m *MockAPIStreamService) ParseFileIndex(index string, fileCount int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseFileIndex", index, fileCount)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseFileIndex indicates an expected call of ParseFileIndex.
func (mr *MockAPIStreamServiceMockRecorder) ParseFileIndex(index, fileCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseFileIndex", reflect.TypeOf((*MockAPIStreamService)(nil).ParseFileIndex), index, fileCount)
}

// ParseLink mocks base method.
func (m *MockAPIStreamService) ParseLink(link, title, poster, category string) (contracts.TorrentSpec, contracts.StreamMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseLink", link, title, poster, category)
	ret0, _ := ret[0].(contracts.TorrentSpec)
	ret1, _ := ret[1].(contracts.StreamMeta)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ParseLink indicates an expected call of ParseLink.
func (mr *MockAPIStreamServiceMockRecorder) ParseLink(link, title, poster, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseLink", reflect.TypeOf((*MockAPIStreamService)(nil).ParseLink), link, title, poster, category)
}

// ParseTorrentFile mocks base method.
func (m *MockAPIStreamService) ParseTorrentFile(reader io.Reader) (contracts.TorrentSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseTorrentFile", reader)
	ret0, _ := ret[0].(contracts.TorrentSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseTorrentFile indicates an expected call of ParseTorrentFile.
func (mr *MockAPIStreamServiceMockRecorder) ParseTorrentFile(reader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseTorrentFile", reflect.TypeOf((*MockAPIStreamService)(nil).ParseTorrentFile), reader)
}

// MockAPIPlaybackService is a mock of PlaybackService interface.
type MockAPIPlaybackService struct {
	ctrl     *gomock.Controller
	recorder *MockAPIPlaybackServiceMockRecorder
	isgomock struct{}
}

// MockAPIPlaybackServiceMockRecorder is the mock recorder for MockAPIPlaybackService.
type MockAPIPlaybackServiceMockRecorder struct {
	mock *MockAPIPlaybackService
}

// NewMockAPIPlaybackService creates a new mock instance.
func NewMockAPIPlaybackService(ctrl *gomock.Controller) *MockAPIPlaybackService {
	mock := &MockAPIPlaybackService{ctrl: ctrl}
	mock.recorder = &MockAPIPlaybackServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIPlaybackService) EXPECT() *MockAPIPlaybackServiceMockRecorder {
	return m.recorder
}

// BuildAllPlaylist mocks base method.
func (m *MockAPIPlaybackService) BuildAllPlaylist(host string, torrents contracts.TorrentPlaylistService) contracts.PlaylistPayload {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildAllPlaylist", host, torrents)
	ret0, _ := ret[0].(contracts.PlaylistPayload)
	return ret0
}

// BuildAllPlaylist indicates an expected call of BuildAllPlaylist.
func (mr *MockAPIPlaybackServiceMockRecorder) BuildAllPlaylist(host, torrents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildAllPlaylist", reflect.TypeOf((*MockAPIPlaybackService)(nil).BuildAllPlaylist), host, torrents)
}

// BuildM3UFromStatus mocks base method.
func (m *MockAPIPlaybackService) BuildM3UFromStatus(tor *state.TorrentStatus, host string, fromLast bool, viewed contracts.ViewedService) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildM3UFromStatus", tor, host, fromLast, viewed)
	ret0, _ := ret[0].(string)
	return ret0
}

// BuildM3UFromStatus indicates an expected call of BuildM3UFromStatus.
func (mr *MockAPIPlaybackServiceMockRecorder) BuildM3UFromStatus(tor, host, fromLast, viewed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildM3UFromStatus", reflect.TypeOf((*MockAPIPlaybackService)(nil).BuildM3UFromStatus), tor, host, fromLast, viewed)
}

// BuildPlaylistByHash mocks base method.
func (m *MockAPIPlaybackService) BuildPlaylistByHash(hash, requestedName string, fromLast bool, host string, torrents contracts.TorrentPlaylistService, viewed contracts.ViewedService) (contracts.PlaylistPayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildPlaylistByHash", hash, requestedName, fromLast, host, torrents, viewed)
	ret0, _ := ret[0].(contracts.PlaylistPayload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildPlaylistByHash indicates an expected call of BuildPlaylistByHash.
func (mr *MockAPIPlaybackServiceMockRecorder) BuildPlaylistByHash(hash, requestedName, fromLast, host, torrents, viewed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildPlaylistByHash", reflect.TypeOf((*MockAPIPlaybackService)(nil).BuildPlaylistByHash), hash, requestedName, fromLast, host, torrents, viewed)
}

// ResolvePlay mocks base method.
func (m *MockAPIPlaybackService) ResolvePlay(hash, index string, unauthorized bool, torrents contracts.TorrentPlayService) (contracts.PlayTarget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolvePlay", hash, index, unauthorized, torrents)
	ret0, _ := ret[0].(contracts.PlayTarget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolvePlay indicates an expected call of ResolvePlay.
func (mr *MockAPIPlaybackServiceMockRecorder) ResolvePlay(hash, index, unauthorized, torrents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolvePlay", reflect.TypeOf((*MockAPIPlaybackService)(nil).ResolvePlay), hash, index, unauthorized, torrents)
}
