// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cache": {
            "post": {
                "description": "Return cache stats.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Return cache stats",
                "parameters": [
                    {
                        "description": "Cache stats request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web_api.cacheReqJS"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cache stats",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/download/{size}": {
            "get": {
                "description": "Download the test file of given size (for speed testing purpose).",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Generates test file of given size",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Test file size (in MB)",
                        "name": "size",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/ffp/{hash}/{id}": {
            "get": {
                "description": "Gather informations using ffprobe.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Gather informations using ffprobe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Torrent hash",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "File index in torrent",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Data returned from ffprobe"
                    }
                }
            }
        },
        "/play/{hash}/{id}": {
            "get": {
                "description": "Play given torrent referenced by infohash and file id.",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Play given torrent by infohash",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Torrent infohash",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "File index in torrent",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Torrent data"
                    }
                }
            }
        },
        "/playlist": {
            "get": {
                "description": "Get HTTP link of torrent in M3U list.",
                "produces": [
                    "audio/x-mpegurl"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Get HTTP link of torrent in M3U list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Torrent hash",
                        "name": "hash",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "From last play file",
                        "name": "fromlast",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/playlistall/all.m3u": {
            "get": {
                "description": "Retrieve all torrents and generates a bundled M3U playlist.",
                "produces": [
                    "audio/x-mpegurl"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Get a M3U playlist with all torrents",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/settings": {
            "post": {
                "description": "Allow to get or set server settings.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Get / Set server settings",
                "parameters": [
                    {
                        "description": "Settings request. Available params for action: get, set, def",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web_api.setsReqJS"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Settings JSON or nothing. Depends on what action has been asked.",
                        "schema": {
                            "$ref": "#/definitions/server_settings.BTSets"
                        }
                    }
                }
            }
        },
        "/shutdown": {
            "get": {
                "description": "Gracefully shuts down server after 1 second.",
                "tags": [
                    "API"
                ],
                "summary": "Shuts down server",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/storage/settings": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieves the current storage preferences for settings and viewed history",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Get storage configuration settings",
                "responses": {
                    "200": {
                        "description": "Storage preferences",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Updates the storage preferences for settings and viewed history. Requires application restart for changes to take effect.",
                "consumes": [
                    "application/json",
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Update storage configuration settings",
                "parameters": [
                    {
                        "description": "Storage preferences to update",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    {
                        "enum": [
                            "json",
                            "bbolt"
                        ],
                        "type": "string",
                        "description": "Settings storage type",
                        "name": "settings",
                        "in": "formData"
                    },
                    {
                        "enum": [
                            "json",
                            "bbolt"
                        ],
                        "type": "string",
                        "description": "Viewed history storage type",
                        "name": "viewed",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Update successful",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid input data",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Read-only mode",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stream": {
            "get": {
                "description": "Multi usage endpoint.",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Multi usage endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Magnet/hash/link to torrent",
                        "name": "link",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "File index in torrent",
                        "name": "index",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Should preload torrent",
                        "name": "preload",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Get statistics from torrent",
                        "name": "stat",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Should save torrent",
                        "name": "save",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Get torrent as M3U playlist",
                        "name": "m3u",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Get M3U from last played file",
                        "name": "fromlast",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start stream torrent",
                        "name": "play",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Set title of torrent",
                        "name": "title",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Set poster link of torrent",
                        "name": "poster",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Set category of torrent, used in web: movie, tv, music, other",
                        "name": "category",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Data returned according to query"
                    }
                }
            }
        },
        "/streams/m3u": {
            "get": {
                "description": "Read-only M3U endpoint. Does not create or modify torrent state.",
                "produces": [
                    "audio/x-mpegurl"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Get torrent playlist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Magnet/hash/link to torrent",
                        "name": "link",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start playlist from last viewed file",
                        "name": "fromlast",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/streams/play": {
            "get": {
                "description": "Command endpoint for streaming torrent file by index.",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Play torrent file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Magnet/hash/link to torrent",
                        "name": "link",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "File index in torrent",
                        "name": "index",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Should preload torrent before stream",
                        "name": "preload",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Torrent title",
                        "name": "title",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Poster URL",
                        "name": "poster",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Torrent category",
                        "name": "category",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Torrent data"
                    }
                }
            }
        },
        "/streams/save": {
            "post": {
                "description": "Command endpoint that saves torrent metadata without streaming.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Save torrent metadata to DB",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Magnet/hash/link to torrent",
                        "name": "link",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Torrent title",
                        "name": "title",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Poster URL",
                        "name": "poster",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Torrent category",
                        "name": "category",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/streams/stat": {
            "get": {
                "description": "Read-only status endpoint. Does not create or modify torrent state.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Get torrent runtime status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Magnet/hash/link to torrent",
                        "name": "link",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server_torr_state.TorrentStatus"
                        }
                    }
                }
            }
        },
        "/tmdb/settings": {
            "get": {
                "description": "Get TMDB API configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Get TMDB settings",
                "responses": {
                    "200": {
                        "description": "TMDB settings",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/torrent/upload": {
            "post": {
                "description": "Only one file support.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Add .torrent file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Torrent file to insert",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Save to DB",
                        "name": "save",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Torrent title",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Torrent category",
                        "name": "category",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Torrent poster",
                        "name": "poster",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Torrent data",
                        "name": "data",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Torrent status",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/torrents": {
            "post": {
                "description": "Allow to list, add, remove, get, set, drop, wipe torrents on server. The action depends of what has been asked.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Handle torrents informations",
                "parameters": [
                    {
                        "description": "Torrent request. Available params: add, get, set, rem, list, drop, wipe.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web_api.torrReqJS"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/torznab/search": {
            "get": {
                "description": "Makes a torznab search.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Makes a torznab search",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Torznab query",
                        "name": "query",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Torznab torrent search result(s)",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/torznab.TorrentDetails"
                            }
                        }
                    }
                }
            }
        },
        "/viewed": {
            "post": {
                "description": "Allow to set, list or remove viewed torrents from server.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Set / List / Remove viewed torrents",
                "parameters": [
                    {
                        "description": "Viewed torrent request. Available params for action: set, rem, list",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web_api.viewedReqJS"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/server_settings.Viewed"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "server_settings.BTSets": {
            "type": "object",
            "properties": {
                "adaptiveRAMaxMB": {
                    "type": "integer"
                },
                "adaptiveRAMinMB": {
                    "description": "Adaptive read-ahead bounds for streaming readers, in MB.\n0 values fallback to safe defaults.",
                    "type": "integer"
                },
                "cacheSize": {
                    "description": "Cache",
                    "type": "integer",
                    "format": "int64"
                },
                "connectionsLimit": {
                    "type": "integer"
                },
                "coreProfile": {
                    "description": "CoreProfile controls predefined kernel tuning presets.\nAllowed: custom, low-end, balanced, high-throughput, nas.",
                    "type": "string"
                },
                "disableDHT": {
                    "type": "boolean"
                },
                "disablePEX": {
                    "type": "boolean"
                },
                "disableTCP": {
                    "type": "boolean"
                },
                "disableUPNP": {
                    "type": "boolean"
                },
                "disableUTP": {
                    "type": "boolean"
                },
                "disableUpload": {
                    "type": "boolean"
                },
                "diskSyncIntervalMS": {
                    "description": "DiskSyncIntervalMS is used only for \"periodic\" policy.",
                    "type": "integer"
                },
                "diskSyncPolicy": {
                    "description": "Disk write pipeline controls.\nDiskSyncPolicy: \"none\" | \"periodic\" | \"always\"",
                    "type": "string"
                },
                "diskWriteBatchSize": {
                    "description": "DiskWriteBatchSize controls sequential write batching.",
                    "type": "integer"
                },
                "downloadRateLimit": {
                    "description": "in kb, 0 - inf",
                    "type": "integer"
                },
                "enableDLNA": {
                    "description": "DLNA",
                    "type": "boolean"
                },
                "enableDebug": {
                    "description": "debug logs",
                    "type": "boolean"
                },
                "enableIPv6": {
                    "description": "BT Config",
                    "type": "boolean"
                },
                "enableProxy": {
                    "description": "P2P Proxy",
                    "type": "boolean"
                },
                "enableRutorSearch": {
                    "description": "Rutor",
                    "type": "boolean"
                },
                "enableTorznabSearch": {
                    "description": "Torznab",
                    "type": "boolean"
                },
                "forceEncrypt": {
                    "description": "Torrent",
                    "type": "boolean"
                },
                "friendlyName": {
                    "type": "string"
                },
                "maxConcurrentStreams": {
                    "description": "Stream admission control\nMaxConcurrentStreams: 0 -\u003e auto (2 * GOMAXPROCS), \u003e0 -\u003e fixed limit",
                    "type": "integer"
                },
                "metadataQueueSize": {
                    "description": "MetadataQueueSize: 0 -\u003e auto (256)",
                    "type": "integer"
                },
                "metadataWorkers": {
                    "description": "Background metadata finalization worker pool.\nMetadataWorkers: 0 -\u003e auto (max(2, GOMAXPROCS/2))",
                    "type": "integer"
                },
                "peersListenPort": {
                    "type": "integer"
                },
                "preloadCache": {
                    "description": "in percent",
                    "type": "integer"
                },
                "preloadQueueSize": {
                    "description": "PreloadQueueSize: 0 -\u003e auto (32)",
                    "type": "integer"
                },
                "preloadWorkers": {
                    "description": "Preload worker pool.\nPreloadWorkers: 0 -\u003e auto (1)",
                    "type": "integer"
                },
                "proxyHosts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "readerReadAHead": {
                    "description": "in percent, 5%-100%, [...S__X__E...] [S-E] not clean",
                    "type": "integer"
                },
                "removeCacheOnDrop": {
                    "type": "boolean"
                },
                "responsiveMode": {
                    "description": "Reader",
                    "type": "boolean"
                },
                "retrackersMode": {
                    "description": "0 - don` + "`" + `t add, 1 - add retrackers (def), 2 - remove retrackers 3 - replace retrackers",
                    "type": "integer"
                },
                "showFSActiveTorr": {
                    "description": "FS",
                    "type": "boolean"
                },
                "sslCert": {
                    "type": "string"
                },
                "sslKey": {
                    "type": "string"
                },
                "sslPort": {
                    "description": "HTTPS",
                    "type": "integer"
                },
                "storeSettingsInJSON": {
                    "description": "Storage preferences",
                    "type": "boolean"
                },
                "storeViewedInJSON": {
                    "type": "boolean"
                },
                "streamQueueSize": {
                    "description": "StreamQueueSize: 0 -\u003e auto (2 * effective max streams), \u003e0 -\u003e fixed queue limit",
                    "type": "integer"
                },
                "streamQueueWaitSec": {
                    "description": "StreamQueueWaitSec: max wait time for queue slot acquisition",
                    "type": "integer"
                },
                "tmdbsettings": {
                    "description": "TMDB",
                    "allOf": [
                        {
                            "$ref": "#/definitions/settings.TMDBConfig"
                        }
                    ]
                },
                "torrentDisconnectTimeout": {
                    "description": "in seconds",
                    "type": "integer"
                },
                "torrentsSavePath": {
                    "type": "string"
                },
                "torznabUrls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/settings.TorznabConfig"
                    }
                },
                "uploadRateLimit": {
                    "description": "in kb, 0 - inf",
                    "type": "integer"
                },
                "useDisk": {
                    "description": "Disk",
                    "type": "boolean"
                },
                "warmDiskCacheSizeMB": {
                    "description": "Warm disk cache (tier-2) controls, in MB/minutes.\n0 values fallback to safe defaults.",
                    "type": "integer",
                    "format": "int64"
                },
                "warmDiskCacheTTLMin": {
                    "type": "integer"
                }
            }
        },
        "server_settings.Viewed": {
            "type": "object",
            "properties": {
                "file_index": {
                    "type": "integer"
                },
                "hash": {
                    "type": "string"
                }
            }
        },
        "server_torr_state.TorrentFileStat": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "length": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "server_torr_state.TorrentStat": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5
            ],
            "x-enum-varnames": [
                "TorrentAdded",
                "TorrentGettingInfo",
                "TorrentPreload",
                "TorrentWorking",
                "TorrentClosed",
                "TorrentInDB"
            ]
        },
        "server_torr_state.TorrentStatus": {
            "type": "object",
            "properties": {
                "active_peers": {
                    "type": "integer"
                },
                "bit_rate": {
                    "type": "string"
                },
                "bytes_read": {
                    "type": "integer"
                },
                "bytes_read_data": {
                    "type": "integer"
                },
                "bytes_read_useful_data": {
                    "type": "integer"
                },
                "bytes_written": {
                    "type": "integer"
                },
                "bytes_written_data": {
                    "type": "integer"
                },
                "category": {
                    "type": "string"
                },
                "chunks_read": {
                    "type": "integer"
                },
                "chunks_read_useful": {
                    "type": "integer"
                },
                "chunks_read_wasted": {
                    "type": "integer"
                },
                "chunks_written": {
                    "type": "integer"
                },
                "connected_seeders": {
                    "type": "integer"
                },
                "data": {
                    "type": "string"
                },
                "download_speed": {
                    "type": "number"
                },
                "duration_seconds": {
                    "type": "number"
                },
                "file_stats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/server_torr_state.TorrentFileStat"
                    }
                },
                "half_open_peers": {
                    "type": "integer"
                },
                "hash": {
                    "type": "string"
                },
                "loaded_size": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "pending_peers": {
                    "type": "integer"
                },
                "pieces_dirtied_bad": {
                    "type": "integer"
                },
                "pieces_dirtied_good": {
                    "type": "integer"
                },
                "poster": {
                    "type": "string"
                },
                "preload_size": {
                    "type": "integer"
                },
                "preloaded_bytes": {
                    "type": "integer"
                },
                "stat": {
                    "$ref": "#/definitions/server_torr_state.TorrentStat"
                },
                "stat_string": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "torrent_size": {
                    "type": "integer"
                },
                "torrs_hash": {
                    "type": "string"
                },
                "total_peers": {
                    "type": "integer"
                },
                "upload_speed": {
                    "type": "number"
                }
            }
        },
        "settings.TMDBConfig": {
            "type": "object",
            "properties": {
                "apikey": {
                    "description": "TMDB API Key",
                    "type": "string"
                },
                "apiurl": {
                    "description": "Base API URL (default: https://api.themoviedb.org)",
                    "type": "string"
                },
                "imageURL": {
                    "description": "Image URL (default: https://image.tmdb.org)",
                    "type": "string"
                },
                "imageURLRu": {
                    "description": "Image URL for Russian users (default: https://imagetmdb.com)",
                    "type": "string"
                }
            }
        },
        "settings.TorznabConfig": {
            "type": "object",
            "properties": {
                "host": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "torznab.TorrentDetails": {
            "type": "object",
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "createDate": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "magnet": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "peer": {
                    "type": "integer"
                },
                "seed": {
                    "type": "integer"
                },
                "size": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "web_api.cacheReqJS": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                }
            }
        },
        "web_api.setsReqJS": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "sets": {
                    "$ref": "#/definitions/server_settings.BTSets"
                }
            }
        },
        "web_api.torrReqJS": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "data": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "poster": {
                    "type": "string"
                },
                "save_to_db": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "web_api.viewedReqJS": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "file_index": {
                    "type": "integer"
                },
                "hash": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8090",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "TorrServer API",
	Description:      "Minimalist torrent streaming server API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
